version: '3.9'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_dev
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  dbdata:
